Fix some problem, but part of tests doesn't work
OlehYakovenko/slideshow pull request #1
Opened 2024-12-18 18:58 UTC by OlehYakovenko

2024-12-18 19:36 UTC, s-barabash requested changes

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/controller/ImageController.java
> +  public ImageEntity addImage(@RequestBody @Validated AddImageRequest request) {
Do not use entity for response

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/controller/ImageController.java
> +  @PostMapping()
Could you please remove braces

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/controller/ImageController.java
> +  @GetMapping()
Could you please remove braces

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/controller/SlideshowController.java
> +  @PostMapping()
Could you please remove braces

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/controller/SlideshowController.java
>      var imageDataList = request.images().stream()
You do not need this mapping just get list from request and send it to service

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/dto/ImageData.java
> +@Builder
does it work with builder annotation?

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/dto/ImageResult.java
> +@Builder
does it work with builder annotation?

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/dto/ImageSearchResponse.java
>  @Builder
does it work with builder annotation?

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/ImageService.java
> +            .associatedSlideshows(Collections.emptyList())
why it is empty list?

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/KafkaLoggingService.java
>    private final KafkaTemplate<String, String> kafkaTemplate;
Let's send the object

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/KafkaLoggingService.java
> +    Message<String> msg = MessageBuilder.withPayload(logMessage)
Use producer record
You may use this record as an example https://github.com/dilipsundarraj1/kafka-for-developers-using-spring-boot/blob/main/library-events-producer/src/main/java/com/learnkafka/producer/LibraryEventProducer.java

2024-12-18 19:36 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/UrlValidationService.java
>    public void validateImageUrl(String url) {
You should also check the file not only url content type

2024-12-19 06:46 UTC, OlehYakovenko commented on src/main/java/com/practice/slideshow/dto/ImageResult.java
> +@Builder
yes

2024-12-19 11:32 UTC, s-barabash requested changes

2024-12-19 11:32 UTC, s-barabash commented on src/main/java/com/practice/slideshow/controller/ImageController.java
> +    return ImageResponse.fromEntity(image);
It would be better if service returns image response

2024-12-19 11:32 UTC, s-barabash commented on src/main/java/com/practice/slideshow/controller/SlideshowController.java
>      return slideshow.getId();
are we sure that we need to return only id?

2024-12-19 11:32 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/KafkaLoggingService.java
> +  private final KafkaTemplate<String, ImageResponse> kafkaTemplate;
it should be string json or string string. You are not using avro as result there could be some issues

2024-12-19 11:32 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/KafkaLoggingService.java
> +  public void logAction(String actionType, ImageEntity entity) {
it is not correct approach please use this link as an example https://github.com/dilipsundarraj1/kafka-for-developers-using-spring-boot/blob/main/library-events-producer/src/main/java/com/learnkafka/producer/LibraryEventProducer.java

2024-12-21 12:24 UTC, s-barabash commented on src/main/java/com/practice/slideshow/controller/SlideshowController.java
> +  public void proofOfPlay(@PathVariable Long id, @PathVariable Long imageId) {
Should we return the whole object?

2024-12-21 12:25 UTC, s-barabash commented on src/main/java/com/practice/slideshow/dto/ImageMapper.java
> +public class ImageMapper {
this class should be in mapper package

2024-12-21 12:32 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/ImageService.java
> +      var associatedSlideshows = slideshowRepository.findByImageId(i.getId())
it does not look right to have separate call for each image to find associated image could you please create separate query to retrieve all related data

2024-12-21 12:35 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/SlideshowService.java
> +      var image = ImageMapper.mapToEntity(imageService.addImage(data.url(), data.duration()));
move it to separate method

2024-12-21 14:52 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/ImageService.java
> +    kafkaLoggingService.logAction(new LogEvent(image.getId(), LogEventType.DELETE_IMAGE));
this action should be after delete action

2024-12-21 14:55 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/KafkaLoggingService.java
> +    } catch (JsonProcessingException e) {
You do not need it please remove it

2024-12-21 14:55 UTC, s-barabash commented on src/main/java/com/practice/slideshow/service/KafkaLoggingService.java
> +      throws JsonProcessingException {
it does not throw an exception

2024-12-21 15:12 UTC, merged